spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true


  sql:
    init:
      mode: never
  application:
    name: user-service

server:
  port: 0
eureka:
  instance:
    hostname: localhost