spring:
  application:
    name: identity-server
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/distcomp
    username: postgres
    password: postgres

    driver-class-name: org.postgresql.Driver

server:
  port: 9000

token:
  signing:
    key: 1234567890123456789012345678901223456789012345678901234567890123
eureka:
  instance:
    hostname: localhost